# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  version: "13.4.2"

package:
  name: "mist"
  version: 0.1.0

source:
  - path: ./src
  # - path: ./LICENSE

build:
  # files:
  #   - src/mist/*.mojo
  script:
    - mkdir -p ${PREFIX}/lib/mojo
    - mojo package mist -o ${PREFIX}/lib/mojo/mist.mojopkg

requirements:
  run:
    - max >= 24.5.0.dev2024083105
    - gojo == 0.1.1
    - hue == 0.1.0

# tests:
#   - script:
#       # commands to run to test the package. If any of the commands
#       # returns with an error code, the test is considered failed.
#       - mojo test test/
#       - ls -la info/recipe
#       - cp ${PREFIX}/lib/mojo/mist.mojopkg info/recipe/test/mist.mojopkg
#       - mojo test info/recipe/test/

#     # requirements:
#     #   run:
#     #     - mojo

#     files:
#       # Extra files to be copied to the test directory from the "work directory"
#       source:
#         - ../src/
#         - ../test/

about:
  homepage: https://github.com/thatstoasty/mist
  license: MIT
  license_file: LICENSE
  summary: mist lets you safely use advanced styling options on the terminal
  repository: https://github.com/thatstoasty/mist
