# ANSI Operations
comptime ESC = "\x1b"
"""Escape character."""
comptime BEL = "\x07"
"""Bell character."""
comptime CSI = "\x1b["
"""Control Sequence Introducer."""
comptime OSC = "\x1b]"
"""Operating System Command."""
comptime ST = "\x1b\\"
"""String Terminator."""
